version: '3'
services:
#  namenode:
#      image: uhopper/hadoop-namenode
#      hostname: namenode
#      ports:
#        - "50070:50070"
#        - "8020:8020"
#      volumes:
#        - /Users/dionrats/Nextcloud/school/Leerjaar_4/Stage/Document Systeem/hadoopdata:/hadoop/dfs/name
#      environment:
#        - CLUSTER_NAME=hadoop-cluster
#      networks:
#        - prototypes
#
#  datanode:
#    image: uhopper/hadoop-datanode
#    depends_on:
#      - namenode
#    volumes:
#      - /Users/dionrats/Nextcloud/school/Leerjaar_4/Stage/Document Systeem/hadoopdata:/hadoop/dfs/data
#    environment:
#      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
#    networks:
#      - prototypes

  namenode:
    image: uhopper/hadoop-namenode
#    hostname: namenode
#    container_name: namenode
#    domainname: hadoop
#    net: hadoop
    ports:
      - 50070:50070
      - 9000:9000
      - 54310:54310
    volumes:
      - /Users/dionrats/Nextcloud/school/Leerjaar_4/Stage/Document Systeem/hadoopdata/namenode:/hadoop/dfs/name
    environment:
#      - GANGLIA_HOST=<gmond-receiver-host>
      - CLUSTER_NAME=testcluster
    networks:
      - prototypes

  datanode:
    image: uhopper/hadoop-datanode
#    hostname: datanode
#    container_name: datanode
#    domainname: hadoop
#    net: hadoop
    volumes:
      - /Users/dionrats/Nextcloud/school/Leerjaar_4/Stage/Document Systeem/hadoopdata/datanode:/hadoop/dfs/data
    environment:
#      - GANGLIA_HOST=<gmond-receiver-host>
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    networks:
      - prototypes

networks:
  prototypes:
    driver: bridge